In [2]:
import numpy as np
#作业图中的转移矩阵
a = np.array([[0,0,0, 1/3, 0, 0],
			[1/4,0, 0, 0, 1/2,0],
			[0, 0, 0,1/3, 1/2,0],
			[1/4, 0,0, 0, 0,1],
            [1/4, 0,1, 1/3, 0,0],
            [1/4, 0,0, 0, 0,0]])
#假设每个点的初始影响力相同
w = np.array([1/6, 1/6,1/6,1/6,1/6,1/6])

print(a)


[[0.         0.         0.         0.33333333 0.         0.        ]
 [0.25       0.         0.         0.         0.5        0.        ]
 [0.         0.         0.         0.33333333 0.5        0.        ]
 [0.25       0.         0.         0.         0.         1.        ]
 [0.25       0.         1.         0.33333333 0.         0.        ]
 [0.25       0.         0.         0.         0.         0.        ]]


In [3]:
print(w)

[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]


In [4]:
#简化模型
def work(a, w):
	for i in range(100):
		w = np.dot(a, w)
		print(w)

#随机浏览模型
def random_work(a, w, n):
	d = 0.85
	for i in range(100):
		w = (1-d)/n + d*np.dot(a, w)
		print(w)


In [5]:
work(a, w)#图中b点存在等级泄露，最终并没有收敛

[0.05555556 0.125      0.13888889 0.20833333 0.26388889 0.04166667]
[0.06944444 0.14583333 0.20138889 0.05555556 0.22222222 0.01388889]
[0.01851852 0.12847222 0.12962963 0.03125    0.23726852 0.01736111]
[0.01041667 0.12326389 0.12905093 0.02199074 0.14467593 0.00462963]
[0.00733025 0.07494213 0.07966821 0.0072338  0.13898534 0.00260417]
[0.00241127 0.07132523 0.07190394 0.00443673 0.08391204 0.00183256]
[0.00147891 0.04255883 0.04343493 0.00243538 0.07398566 0.00060282]
[0.00081179 0.03736256 0.03780462 0.00097254 0.04461645 0.00036973]
[0.00032418 0.02251117 0.02263241 0.00057268 0.03833175 0.00020295]
[1.90891847e-04 1.92469216e-02 1.93567682e-02 2.83993484e-04
 2.29043424e-02 8.10453104e-05]
[9.46644947e-05 1.14998942e-02 1.15468357e-02 1.28768272e-04
 1.94991556e-02 4.77229617e-05]
[4.29227573e-05 9.77324393e-03 9.79250056e-03 7.13890854e-05
 1.16134246e-02 2.36661237e-05]
[2.37963618e-05 5.81744298e-03 5.83050865e-03 3.43968130e-05
 9.82702761e-03 1.07306893e-05]
[1.14656043e-05 

In [6]:
random_work(a,w,6)#在随机浏览模型下，最终都收敛了

[0.07222222 0.13125    0.14305556 0.20208333 0.24930556 0.06041667]
[0.08225694 0.14630208 0.18821181 0.09170139 0.21920139 0.04034722]
[0.05098206 0.13564019 0.14414265 0.07677474 0.2284417  0.0424796 ]
[0.04675284 0.13292141 0.14384056 0.07194135 0.18010778 0.03583369]
[0.04538338 0.11148079 0.12192919 0.06539361 0.17758284 0.03493498]
[0.04352819 0.11011668 0.1190009  0.0643387  0.15681197 0.03464397]
[0.0432293  0.10089483 0.10987439 0.06369711 0.1536298  0.03424974]
[0.04304752 0.09947889 0.10834018 0.06329851 0.14562697 0.03418623]
[0.04293458 0.09603906 0.10482604 0.06320589 0.14417133 0.0341476 ]
[0.04290834 0.09539641 0.10418115 0.06314906 0.14113407 0.0341236 ]
[0.04289223 0.0941     0.10287421 0.06312308 0.14056423 0.03411802]
[0.04288487 0.0938544  0.10262467 0.06311492 0.13944255 0.0341146 ]
[0.04288256 0.09337612 0.10214564 0.06311044 0.13922657 0.03411304]
[0.04288129 0.09328383 0.10205258 0.06310862 0.13881763 0.03411254]
[0.04288078 0.09310977 0.10187827 0.06310794 0.1